repos:
  # Default checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-ast
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-merge-conflict
    - id: no-commit-to-branch
    - id: pretty-format-json

  # Force good order on imports
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    - id: reorder-python-imports

  # Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
