[tool.black]
line-length = 100

[tool.poetry]
name = "vcrypto"
version = "3.0.0"
description = "Utility to easily store password/secrets"
authors = ["Arnau Villoro <arnau@villoro.com>"]
maintainers = ["Arnau Villoro <arnau@villoro.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/villoro/vcrypto"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Manufacturing",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
]

[tool.poetry.dependencies]
python = "^3.6.1"
cryptography = "^36.0.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pytest = "^5.4.2"
pre-commit = "^2.3.0"
pyyaml = "^5.3.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
