name: Publish package
env:
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install uv
      run: pip install uv

    - name: Set up virtual environment
      run: uv venv --python=3.12 .venv

    - name: Install dependencies
      run: uv pip install --no-dev

    - name: Build
      run: uv pip wheel --no-deps --wheel-dir dist .

    - name: Publish
      run: uv pip upload -u villoro -p $PYPI_PASSWORD dist/*
