name: Publish
env:
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

on:
  # push:
  #   branches: [main]

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish_pypi:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install uv
      run: pip install uv

    - name: Build
      run: uv build

    - name: Publish
      run: uv publish -u villoro -p $PYPI_PASSWORD
