name: Publish

permissions:
  id-token: write

on:
  push:
    branches:
      - main
    paths:
      - pyproject.toml

jobs:
  publish_pypi:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install uv
      run: pip install uv

    - name: Build
      run: uv build

    - name: Publish
      run: uv publish
